### PR TITLE
Remove UIWebView

### PR DESCRIPTION
**Pull request by Lax**
Deprecated https://developer.apple.com/documentation/uikit/uiwebview

* needs releasing new gem version
* Please merge #222 first

### CODE REVIEW

**Comment by wndxlori** [comment]
Perhaps we could replace with the WKWebView equivalent?  
https://developer.apple.com/documentation/webkit/wkwebview/1415017-evaluatejavascript?language=objc

**Comment by Lax** [comment]
WKWebView differs from UIWebView from many aspects:
First, WKWebView#evaluatejavascript uses an async way to run javascripts.
Second, UIWebView is available on iOS only, WKWebView is available on both iOS and macOS.

Testing is failing on both travis-ci and local now, I will try to fix this later.

**Comment by Lax** [comment]
`rake spec` passes on my local machine (macOS 10.15.2, RubyMotion 7.1), but it still fails on travis-ci.com(macOS 10.14, RM 7.1).
Any ideas?

**Comment by Lax** [comment]
@andrewhavens This PR together with #222, needs publishing a new version to rubygems.org.

**Pull request merged**
